language: node_js
node_js:
  - 8

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-beta
  include:
    - stage: 'Tests'
      script:
        - yarn commitlint-travis
        - yarn lint:js
        - yarn lint:hbs
        - yarn test

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - stage: 'Additional Tests'
      env: EMBER_TRY_SCENARIO=minimum-supported-version
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=fastboot-addon-tests

    - stage: deploy
      if: (branch = master or tag is present) and type = push
      script: node_modules/.bin/ember deploy production

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
